import Head from 'next/head';
import PageWrapper from '../components/PageWrapper/PageWrapper';
import TransactionSection from '../components/TransactionSection/TransactionSection';

export default function Home() {
  return (
    <div className={'App'}>
      <Head>
        <title>Perfin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        <TransactionSection />
      </PageWrapper>
    </div>
  )
}
